name: cd

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Github Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - id: tag
      uses: dawidd6/action-get-tag@v1
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/ampelproject/catalog-server:${{steps.tag.outputs.tag}}, ghcr.io/ampelproject/catalog-server:k8s
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
      
