name: cd

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@27d0a4f181a40b142cce983c5393082c365d1480 # v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@f211e3e9ded2d9377c8cadc4489a4e38014bc4c9 # v1
    - name: Login to Github Packages
      uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7 # v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - id: tag
      uses: dawidd6/action-get-tag@727a6f0a561be04e09013531e73a3983a65e3479 # v1
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a # v2
      with:
        push: true
        tags: ghcr.io/ampelproject/catalog-server:${{steps.tag.outputs.tag}}, ghcr.io/ampelproject/catalog-server:k8s
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
      
