name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:8
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: 12345
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v4
    - name: "Set up environment"
      uses: packetcoders/action-setup-cache-python-poetry@v1.2.0
      with:
        # renovate: datasource=conda depName=conda-forge/python
        python-version: "3.12.6"
        # renovate: datasource=pypi depName=poetry versioning=pep440
        poetry-version: "1.8.3"
        install-args: --all-extras
    - name: Install root
      run: poetry run pip install -e . --no-deps
    - name: Lint with mypy
      run: |
        poetry run mypy app
    # - name: Populate test catalog
    #   run: |
    #     tests/test-data/minimongodumps/restore.sh
    #   env:
    #     MONGO_INITDB_ROOT_USERNAME: root
    #     MONGO_INITDB_ROOT_PASSWORD: 12345
    #     MONGODUMP_DIR: tests/test-data/minimongodumps
    - name: Test with pytest
      run: |
        MONGO_URI=mongodb://nobody:seekrit@localhost:27017 poetry run pytest
