name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:5.0.6
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: 12345
        ports:
          - 27019:27019

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Set up Poetry
      uses: abatilo/actions-poetry@v2.0.0
    - name: Install dependencies
      run: |
        poetry install
    - name: Lint with mypy
      run: |
        poetry run mypy app
    - name: Populate test catalog
      run: |
        tests/test-data/minimongodumps/restore.sh
      env:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: 12345

    - name: Test with pytest
      run: |
        MONGO_URI=mongodb://nobody:seekrit@localhost:27019 poetry run pytest
